name: Windows Build

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Install CMake
      run: choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      
    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat -disableMetrics
        cd ..
        
    - name: Install dependencies
      shell: cmd
      run: |
        call vcpkg\vcpkg install ^
          exiv2:x64-windows ^
          tiff:x64-windows ^
          libpng:x64-windows ^
          libraw:x64-windows ^
          qt5-base:x64-windows
        
    - name: Download and setup ALGLIB
      shell: cmd
      run: |
        mkdir alglib
        curl -L https://www.alglib.net/translator/re/alglib-3.19.0.cpp.zip -o alglib.zip || (
          echo "Failed to download ALGLIB, trying alternative source..."
          curl -L https://github.com/HDRMerge/hdrmerge/releases/download/alglib/alglib-3.19.0.cpp.zip -o alglib.zip
        )
        tar -xf alglib.zip -C alglib || (
          7z x alglib.zip -oalglib -y
        )
        dir alglib
        
    - name: Configure build
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 ^
