name: Windows Build

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install -y exiv2 libtiff libpng libraw qt5-default
        
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Create build directory
      run: mkdir build && cd build
      
    - name: Configure with CMake
      run: cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build-type || 'Release' }}
      
    - name: Build
      run: cmake --build . --config ${{ github.event.inputs.build-type || 'Release' }}
      
    - name: Package artifacts
      run: |
        mkdir artifact
        copy ${{ github.event.inputs.build-type || 'Release' }}\hdrmerge.exe artifact\
        copy ${{ github.event.inputs.build-type || 'Release' }}\*.dll artifact\
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hdrmerge-windows
        path: artifact/*
        if-no-files-found: error
