name: Windows Build

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Install CMake
      run: choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      
    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        
    - name: Install dependencies
      run: .\vcpkg\vcpkg install exiv2 libtiff libpng libraw[lcms] qt5-base
        
    - name: Configure environment
      run: |
        echo "VCPKG_ROOT=$PWD\vcpkg" >> $env:GITHUB_ENV
        echo "PATH=$PWD\vcpkg\installed\x64-windows\bin;$env:PATH" >> $env:GITHUB_ENV
        
    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" `
          -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build-type || 'Release' }}
      
    - name: Build
      run: |
        cd build
        cmake --build . --config ${{ github.event.inputs.build-type || 'Release' }} --target install
      
    - name: Package artifacts
      run: |
        mkdir artifact
        copy build\${{ github.event.inputs.build-type || 'Release' }}\hdrmerge.exe artifact\
        copy $env:VCPKG_ROOT\installed\x64-windows\bin\*.dll artifact\
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hdrmerge-windows-${{ github.event.inputs.build-type || 'Release' }}
        path: artifact/*
        if-no-files-found: error
