name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install exiv2 libtiff libpng libraw qt5-default
        
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Create build directory
      run: mkdir build && cd build
      
    - name: Configure with CMake
      run: cmake .. -G "Visual Studio 17 2022" -A x64
      
    - name: Build
      run: cmake --build . --config Release
      
    - name: Package artifacts
      run: |
        mkdir artifact
        copy Release\hdrmerge.exe artifact\
        copy Release\*.dll artifact\
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hdrmerge-windows
        path: artifact/*
