name: Windows Build

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Install CMake
      run: choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      
    - name: Clean vcpkg environment
      run: |
        # Clear any existing vcpkg environment variables
        reg delete "HKCU\Environment" /v "VCPKG_ROOT" /f 2>nul || true
        setx VCPKG_ROOT ""
      
    - name: Setup fresh vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        git checkout 2024.06.12
        .\bootstrap-vcpkg.bat
        cd ..
        
    - name: Install dependencies
      shell: cmd
      run: |
        vcpkg\vcpkg install ^
          --vcpkg-root="%cd%\vcpkg" ^
          exiv2:x64-windows ^
          tiff:x64-windows ^
          libpng:x64-windows ^
          "libraw[lcms]:x64-windows" ^
          qt5-base:x64-windows
        
    - name: Configure build
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 ^
          -DCMAKE_TOOLCHAIN_FILE="$env:GITHUB_WORKSPACE\vcpkg\scripts\buildsystems\vcpkg.cmake" ^
          -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build-type || 'Release' }}
      
    - name: Build project
      run: |
        cd build
        cmake --build . --config ${{ github.event.inputs.build-type || 'Release' }} --target install
      
    - name: Package artifacts
      run: |
        mkdir artifact
        copy build\${{ github.event.inputs.build-type || 'Release' }}\hdrmerge.exe artifact\
        copy vcpkg\installed\x64-windows\bin\*.dll artifact\
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hdrmerge-windows-${{ github.event.inputs.build-type || 'Release' }}
        path: artifact/*
        if-no-files-found: error
